# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: tomristt/gatewayserver
  tag: s17

containerPort: 8072

service:
  type: ClusterIP
  port: 8080
  targetPort: 8072

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false