build:
  version: "3.0"

accounts:
  message: "Welcome to Wallet-wave accounts related local APIs "
  contactDetails:
    name: "Tomris Teymurlu - Developer"
    email: "tomristt9@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345